"""
Tests for load.postgres against a real, throwaway Postgres
server. Migrations only ever write to that throwaway server; production is
only *read*, once, for the current definitions of the `teams` and `games`
tables and the `team_games` view, so the test database always matches the
real one and the real constraints are exercised too.

The point is the all-or-nothing guarantee - a successful migration replaces
exactly one season, and any failure (a bad row, an unknown team, a failed
whole-season check) leaves the tables exactly as they were.

Skipped when no local Postgres install is found (initdb on PATH, or
Postgres.app on macOS), or when production can't be reached (no
POSTGRES_URL in .env.development.local, or no network).
"""

import datetime
import os
import shutil
import socket
import subprocess
import tempfile

import psycopg2
import pytest

import load.postgres as migration
from util.paths import PROJECT_ROOT
from transform.build_game_records import GameRecord

POSTGRES_APP_BIN = "/Applications/Postgres.app/Contents/Versions/latest/bin"

# Captured before any test points get_postgres_connection at the throwaway server
_connect_to_production = migration.get_postgres_connection


def _table_ddl(cursor, table):
    """CREATE TABLE for one production table, rebuilt from the catalog."""
    cursor.execute("""
        SELECT a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull, a.attidentity,
               pg_get_expr(d.adbin, d.adrelid)
        FROM pg_attribute a
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = %s::regclass AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
    """, (f"public.{table}",))
    columns = []
    for name, type_, not_null, identity, default in cursor.fetchall():
        column = f"{name} {type_}"
        if identity:
            column += " GENERATED ALWAYS AS IDENTITY" if identity == "a" else " GENERATED BY DEFAULT AS IDENTITY"
        elif default is not None:
            column += f" DEFAULT {default}"
        columns.append(column + (" NOT NULL" if not_null else ""))
    cursor.execute("""
        SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid = %s::regclass ORDER BY conname
    """, (f"public.{table}",))
    constraints = [f"CONSTRAINT {name} {definition}" for name, definition in cursor.fetchall()]
    return f"CREATE TABLE {table} ({', '.join(columns + constraints)})"


@pytest.fixture(scope="module")
def production_schema():
    """SQL recreating production's teams, games and team_games (read-only)."""
    env_path = os.path.join(PROJECT_ROOT, ".env.development.local")
    if not os.path.exists(env_path) and not os.getenv("POSTGRES_URL"):
        pytest.skip("no database credentials - run `npm run sync-env` from the project root "
                    "to pull .env.development.local from Vercel")
    try:
        conn = _connect_to_production()
    except Exception as e:
        pytest.skip(f"can't reach production to read the table definitions "
                    f"({e.__class__.__name__}) - check your network connection and POSTGRES_URL")
    try:
        conn.set_session(readonly=True)
        cursor = conn.cursor()
        statements = [_table_ddl(cursor, "teams"), _table_ddl(cursor, "games")]
        cursor.execute("SELECT pg_get_viewdef('public.team_games'::regclass, true)")
        statements.append(f"CREATE VIEW team_games AS {cursor.fetchone()[0]}")
    finally:
        conn.close()
    return statements


def _find_postgres_bin():
    initdb = shutil.which("initdb")
    if initdb:
        return os.path.dirname(initdb)
    if os.path.exists(os.path.join(POSTGRES_APP_BIN, "initdb")):
        return POSTGRES_APP_BIN
    return None


def _free_port():
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


@pytest.fixture(scope="module")
def postgres_dsn():
    """Start a throwaway Postgres server for this module, then delete it."""
    bin_dir = _find_postgres_bin()
    if bin_dir is None:
        pytest.skip("no local Postgres install found")

    data_dir = tempfile.mkdtemp(prefix="moneyline_pg_")
    port = _free_port()
    try:
        subprocess.run([os.path.join(bin_dir, "initdb"), "-D", data_dir, "-U", "test", "-A", "trust"],
                       check=True, capture_output=True)
        # TCP only: a Unix socket path inside a long temp dir can exceed macOS's limit
        subprocess.run([os.path.join(bin_dir, "pg_ctl"), "-D", data_dir, "-w", "-l", os.path.join(data_dir, "log"),
                        "-o", f"-p {port} -c listen_addresses=127.0.0.1 -c unix_socket_directories=''",
                        "start"], check=True, capture_output=True)
        yield f"host=127.0.0.1 port={port} user=test dbname=postgres"
    finally:
        subprocess.run([os.path.join(bin_dir, "pg_ctl"), "-D", data_dir, "-m", "immediate", "stop"],
                       capture_output=True)
        shutil.rmtree(data_dir, ignore_errors=True)


TEAMS = [f"Team {i:02d}" for i in range(30)]


@pytest.fixture
def db(postgres_dsn, production_schema, monkeypatch):
    """Fresh tables matching production's, with 30 test teams and migrations pointed at them."""
    conn = psycopg2.connect(postgres_dsn)
    conn.autocommit = True
    cursor = conn.cursor()
    cursor.execute("DROP VIEW IF EXISTS team_games; DROP TABLE IF EXISTS games; DROP TABLE IF EXISTS teams")
    for statement in production_schema:
        cursor.execute(statement)
    cursor.executemany("INSERT INTO teams (team_id, name) VALUES (%s, %s)", list(enumerate(TEAMS, 1)))
    monkeypatch.setattr(migration, "get_postgres_connection", lambda: psycopg2.connect(postgres_dsn))
    yield cursor
    conn.close()


def _season(season, games_per_team=2):
    """A valid season: teams paired off, each pair playing on consecutive days,
    the home team (first of each pair) winning at -150 / +130."""
    records = []
    for i in range(0, 30, 2):
        for n in range(games_per_team):
            records.append(GameRecord(game_date=datetime.date(season, 11, 1) + datetime.timedelta(days=n),
                                      home=TEAMS[i], away=TEAMS[i + 1], neutral_site=False,
                                      home_won=True, home_odds=-150, away_odds=130))
    return records


def _tables(cursor):
    cursor.execute("SELECT * FROM games ORDER BY seasonstartyear, game_date, home_team_id")
    return cursor.fetchall()


def test_migration_replaces_only_its_own_season(db):
    migration.migrate_season_to_postgres(_season(2024, games_per_team=3), 2024)
    migration.migrate_season_to_postgres(_season(2025, games_per_team=3), 2025)

    inserted = migration.migrate_season_to_postgres(_season(2025, games_per_team=2), 2025)

    assert inserted == 30
    db.execute("SELECT seasonstartyear, COUNT(*) FROM games GROUP BY 1 ORDER BY 1")
    assert db.fetchall() == [(2024, 45), (2025, 30)]


def test_view_shows_each_game_from_both_sides(db):
    migration.migrate_season_to_postgres(_season(2025, games_per_team=2), 2025)

    db.execute("""SELECT team, gamenumber, outcome, winodds, loseodds, opponent, is_home
                  FROM team_games WHERE team IN ('Team 00', 'Team 01') ORDER BY team, gamenumber""")
    assert db.fetchall() == [
        ("Team 00", 1, True, -150, 130, "Team 01", True),
        ("Team 00", 2, True, -150, 130, "Team 01", True),
        ("Team 01", 1, False, 130, -150, "Team 00", False),
        ("Team 01", 2, False, 130, -150, "Team 00", False),
    ]


def test_game_numbers_follow_dates_not_insert_order(db):
    records = _season(2025, games_per_team=3)
    migration.migrate_season_to_postgres(list(reversed(records)), 2025)

    db.execute("SELECT gamenumber, game_date FROM team_games WHERE team = 'Team 00' ORDER BY gamenumber")
    dates = [d for _, d in db.fetchall()]
    assert dates == sorted(dates)


def _assert_failed_migration_changes_nothing(db, bad_records):
    migration.migrate_season_to_postgres(_season(2025), 2025)
    before = _tables(db)

    with pytest.raises(Exception):
        migration.migrate_season_to_postgres(bad_records, 2025)

    assert _tables(db) == before


def test_bad_row_rolls_back_everything(db):
    records = _season(2025)
    records[-1].home_odds = 50  # not valid American odds - rejected by a CHECK
    _assert_failed_migration_changes_nothing(db, records)


def test_unknown_team_rolls_back_everything(db):
    records = _season(2025)
    records[-1].away = "Seattle SuperSonics"  # not in teams
    _assert_failed_migration_changes_nothing(db, records)


def test_team_home_twice_in_a_day_rolls_back_everything(db):
    records = _season(2025)
    records[-1].game_date = records[-2].game_date  # same home team, same date - a UNIQUE constraint
    _assert_failed_migration_changes_nothing(db, records)


def test_missing_teams_fail_season_check_and_roll_back(db):
    records = [r for r in _season(2025) if r.home != "Team 28"]  # Teams 28 and 29 never play
    _assert_failed_migration_changes_nothing(db, records)


def test_team_playing_twice_in_a_day_fails_season_check_and_rolls_back(db):
    records = _season(2025)
    # Team 01 also hosts a game on a day it's already away - every row valid, the season isn't
    records.append(GameRecord(game_date=records[0].game_date, home="Team 01", away="Team 02",
                              neutral_site=False, home_won=True, home_odds=-110, away_odds=-110))
    _assert_failed_migration_changes_nothing(db, records)
